#Configuracion
#Thu May 07 16:56:52 MST 2026
registration.image.last.directory=E\:\\pins\\ICONS
registration.window.height=600
registration.window.width=600
registration.window.x=367
registration.window.y=44
ui.theme=light
users.export.pdf=C\:\\Users\\Sergio Zamora\\Downloads
