#Configuracion
#Thu Jun 04 16:30:16 MST 2026
address.export.pdf=C\:\\Users\\jesus
orders.export.pdf=E\:\\
product.export.pdf=E\:\\
productType.export.pdf=E\:\\
registration.image.last.directory=E\:\\pins\\ICONS
registration.window.height=830
registration.window.width=1550
registration.window.x=-7
registration.window.y=-7
roles.export.pdf=C\:\\Users\\jesus
ui.theme=dark
users.export.pdf=C\:\\Users\\jesus\\OneDrive\\Documentos
