#Configuracion
#Fri Jun 05 16:15:07 MST 2026
orders.export.pdf=
product.export.pdf=
productType.export.pdf=
registration.image.last.directory=
registration.window.height=687
registration.window.width=1295
registration.window.x=-7
registration.window.y=-7
roles.export.pdf=
ui.theme=dark
users.export.pdf=
